dependencies:
- name: cp-kafka
  version: 0.1.0
  repository: file://./charts/cp-kafka
  condition: cp-kafka.enabled
- name: cp-zookeeper
  version: 0.1.0
  repository: file://./charts/cp-zookeeper
  condition: cp-zookeeper.enabled
- name: cp-kafka-connect
  version: 0.1.0
  repository: file://./charts/cp-kafka-connect
  condition: cp-kafka-connect.enabled
